apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: ruoyi-k8s
  labels:
    app: redis
  annotations:
    security.alpha.kubernetes.io/unsafe-sysctls: net.core.somaxconn=65535
spec:
  #securityContext:
    #privileged: true
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        #net:
          #core:
            #somaxconn=511:
    spec:
      containers:
        - name: redis
          image: redis:5.0.6
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 450m
              memory: 1000Mi
            requests:
              cpu: 400m
              memory: 1000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
          command: ["redis-server","--appendonly yes"]
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ruoyi-k8s
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
  selector:
    app: redis
