server:
  port: 80
spring:
  redis:
    host: 8.136.207.182
    port: 6379
    password: Solution#008
    database: 4
  db:
    ip: 8.136.207.182
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${spring.db.ip}:3306/ry-2022?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Solution&*73
k8s:
  namespace: ruoyi-k8s
  podName: ${spring.application.name}